using System;
using System.Collections.Generic;
using System.IO;
using PlainBuffers.CodeGen;
using PlainBuffers.CodeGen.Data;

namespace PlainBuffers.Generators {
  public class CSharpSafeBuffersGenerator : CSharpAbstractGenerator {
    public CSharpSafeBuffersGenerator(string[] namespaces) : base(namespaces) { }

    protected override void WriteHeader(TextWriter writer) {
      writer.WriteLine("// This file is auto-generated by the PlainBuffers compiler");
      writer.WriteLine($"// Generated at {DateTimeOffset.Now:O}");
      writer.WriteLine();

      writer.WriteLine("// ReSharper disable All");
      writer.WriteLine();

      writer.WriteLine("using System;");
      writer.WriteLine("using System.Runtime.InteropServices;");
      writer.WriteLine();
    }

    protected override void WriteEnum(CodeGenEnum enumType, in BlockWriter nsBlock, HashSet<string> valueTypes) {
      if (enumType.IsFlags)
        nsBlock.WriteLine("[Flags]");

      using (var typeBlock = nsBlock.Sub($"public enum {enumType.Name} : {enumType.UnderlyingType}")) {
        for (var i = 0; i < enumType.Items.Length; i++) {
          var item = enumType.Items[i];
          var comma = i < enumType.Items.Length - 1 ? "," : string.Empty;

          typeBlock.WriteLine($"{item.Name} = {item.Value}{comma}");
        }
      }

      valueTypes.Add(enumType.Name);
    }

    protected override void WriteArray(CodeGenArray arrayType, in BlockWriter nsBlock, HashSet<string> valueTypes) {
      using (var typeBlock = nsBlock.Sub($"public readonly ref struct {arrayType.Name}")) {
        typeBlock.WriteLine($"public const int SizeOf = {arrayType.Size};");
        typeBlock.WriteLine($"public const int Length = {arrayType.Length};");

        typeBlock.WriteLine();
        WriteConstructor(arrayType.Name, typeBlock);

        var itemType = arrayType.ItemType;
        var isValueType = valueTypes.Contains(itemType);

        typeBlock.WriteLine();
        WriteCopyToMethod(arrayType.Name, typeBlock);

        typeBlock.WriteLine();
        using (var wdBlock = typeBlock.Sub("public void WriteDefault()"))
        using (var forBlock = wdBlock.Sub("for (var i = 0; i < Length; i++)")) {
          PutWriteDefaultLine(forBlock, "this[i]", itemType, arrayType.ItemDefaultValueInfo);
        }

        typeBlock.WriteLine();
        var sizeExpr = isValueType ? $"sizeof({itemType})" : $"{itemType}.SizeOf";
        var sliceExpr = $"_buffer.Slice(index * {sizeExpr}, {sizeExpr})";
        typeBlock.WriteLine(isValueType ?
          $"public ref {itemType} this[int index] => ref MemoryMarshal.Cast<byte, {itemType}>({sliceExpr})[0];" :
          $"public {itemType} this[int index] => new {itemType}({sliceExpr});");

        typeBlock.WriteLine();
        WriteArrayEnumerator(arrayType.Name, itemType, typeBlock, isValueType);

        typeBlock.WriteLine();
        WriteEqualityOperators(arrayType.Name, typeBlock);
      }
    }

    private static void WriteArrayEnumerator(string array, string item, BlockWriter arrayBlock, bool itemIsValueType) {
      var enumeratorType = $"_EnumeratorOf{array}";
      arrayBlock.WriteLine($"public {enumeratorType} GetEnumerator() => new {enumeratorType}(this);");

      arrayBlock.WriteLine();
      using (var enumeratorBlock = arrayBlock.Sub($"public ref struct {enumeratorType}")) {
        enumeratorBlock.WriteLine($"private readonly {array} _array;");
        enumeratorBlock.WriteLine("private int _index;");

        enumeratorBlock.WriteLine();
        using (var ctorBlock = enumeratorBlock.Sub($"public {enumeratorType}({array} array)")) {
          ctorBlock.WriteLine("_array = array;");
          ctorBlock.WriteLine("_index = -1;");
        }

        enumeratorBlock.WriteLine();
        enumeratorBlock.WriteLine("public bool MoveNext() => ++_index < Length;");
        enumeratorBlock.WriteLine(itemIsValueType
          ? $"public ref {item} Current => ref _array[_index];"
          : $"public {item} Current => _array[_index];");

        enumeratorBlock.WriteLine();
        enumeratorBlock.WriteLine("public void Reset() => _index = -1;");
        enumeratorBlock.WriteLine("public void Dispose() {}");
      }
    }

    protected override void WriteStruct(CodeGenStruct structType, in BlockWriter nsBlock, HashSet<string> valueTypes) {
      using (var typeBlock = nsBlock.Sub($"public readonly ref struct {structType.Name}")) {
        typeBlock.WriteLine($"public const int SizeOf = {structType.Size};");

        if (structType.Padding != 0)
          typeBlock.WriteLine($"private const int _Padding = {structType.Padding};");

        typeBlock.WriteLine();
        WriteConstructor(structType.Name, typeBlock);

        typeBlock.WriteLine();
        foreach (var field in structType.Fields) {
          var isValueType = valueTypes.Contains(field.Type);
          var sizeExpr = isValueType ? $"sizeof({field.Type})" : $"{field.Type}.SizeOf";
          var sliceExpr = $"_buffer.Slice({field.Offset}, {sizeExpr})";
          typeBlock.WriteLine(isValueType?
            $"public ref {field.Type} {field.Name} => ref MemoryMarshal.Cast<byte, {field.Type}>({sliceExpr})[0];" :
            $"public {field.Type} {field.Name} => new {field.Type}({sliceExpr});");
        }

        typeBlock.WriteLine();
        WriteCopyToMethod(structType.Name, typeBlock);

        typeBlock.WriteLine();
        using (var wdBlock = typeBlock.Sub("public void WriteDefault()")) {
          foreach (var field in structType.Fields) {
            PutWriteDefaultLine(wdBlock, field.Name, field.Type, field.DefaultValueInfo);
          }

          if (structType.Padding != 0) {
            wdBlock.WriteLine("GetBuffer().Slice(SizeOf - _Padding, _Padding).Fill(0);");
          }
        }

        typeBlock.WriteLine();
        WriteEqualityOperators(structType.Name, typeBlock);
      }
    }

    private static void WriteConstructor(string type, BlockWriter typeBlock) {
      typeBlock.WriteLine("private readonly Span<byte> _buffer;");
      typeBlock.WriteLine("public Span<byte> GetBuffer() => _buffer;");

      typeBlock.WriteLine();
      using (var ctorBlock = typeBlock.Sub($"public {type}(Span<byte> buffer)")) {
        const string msg = "\"Buffer size doesn't match to the struct size!\"";
        ctorBlock.WriteLine($"if (buffer.Length != SizeOf) throw new InvalidOperationException({msg});");
        ctorBlock.WriteLine("_buffer = buffer;");
      }
    }

    private static void WriteCopyToMethod(string type, BlockWriter typeBlock) {
      typeBlock.WriteLine($"public void CopyTo({type} other) => _buffer.CopyTo(other._buffer);");
    }

    private static void WriteEqualityOperators(string type, in BlockWriter typeBlock) {
      typeBlock.WriteLine($"public static bool operator ==({type} l, {type} r) => l._buffer.SequenceEqual(r._buffer);");
      typeBlock.WriteLine($"public static bool operator !=({type} l, {type} r) => !l._buffer.SequenceEqual(r._buffer);");
      typeBlock.WriteLine();
      typeBlock.WriteLine("public override bool Equals(object obj) => false;");
      typeBlock.WriteLine("public override int GetHashCode() => throw new NotSupportedException();");
    }
  }
}